#ifndef EVENT_DECLARATIONS_H
#define EVENT_DECLARATIONS_H

#define EVENT_CLEAR_OBJECTS					0
#define EVENT_ADD_PROP_OBJECT				1
#define EVENT_ADD_MESH_OBJECT				2
#define EVENT_SPAWN_PLAYER					3
#define EVENT_KILL_GAME_OBJECT				4
#define EVENT_DELETE_GAME_OBJECT			5
#define EVENT_UPDATE_GAME_OBJECT			6
#define EVENT_ADD_SPELL						7
#define EVENT_CHANGE_SPELL					8
#define EVENT_ATTACK						9
											//10 is \n
#define EVENT_DAMAGE						11
#define EVENT_HEAL							12
#define EVENT_FORCE							13
#define EVENT_CENTRAL_FORCE					14
#define EVENT_SPAWN_FULL_HEALTH_KIT			15
#define EVENT_SPAWN_HALF_HEALTH_KIT			16
#define EVENT_CREATE_FIREBALL				17
#define EVENT_CREATE_GRENADE				18
#define EVENT_CREATE_FADING_BEAM_EFFECT		19

#define FUNCTION_COUNT 20

#endif